version: '3'
services:
  owasp-frontend-1:
    image: nukuutos/owasp-frontend-1
    # keep container alive and listen for request after star up
    stdin_open: true
    ports:
      - '3000:3000'
    networks:
      - 'owasp'
  owasp-api-1:
    image: nukuutos/owasp-api-1
    ports:
      - '5000:5000'
    networks:
      - 'owasp'
networks:
  owasp:
    driver: bridge
