version: '3'

services:
  app:
    image: bakenecko/owasp6
    ports:
      - 8000:8000
    networks:
      - 'owasp'
  client-user:
    image: nukuutos/owasp-frontend-6
    ports:
      - 3000:3000
    networks:
      - 'owasp'
  client-victim:
    image: nukuutos/owasp-frontend-6-for-listening
    ports:
      - 3001:3000
    networks:
      - 'owasp'
networks:
  owasp:
    driver: bridge
