version: '3'

services:
  app:
    image: bakenecko/owasp3
    ports:
      - 8000:8000
    networks:
      - 'owasp'
  client:
    image: nukuutos/owasp-frontend-3
    ports:
      - 3000:3000
    networks:
      - 'owasp'
networks:
  owasp:
    driver: bridge
